### ISSUE TITLE
Investigate  dependency on @babel/runtime

### ISSUE THREAD

**Issue by robmcguinness** [Availity/sdk-js#275]
### Current Behavior

https://github.com/Availity/sdk-js/commit/6bc2f8b05ccaa99d4bf5963b94d7a47025519897

### Expected behavior

Packages that do not require that dependency

### Suggested solution(s)

Maybe remove?

**Comment by chrishavekost** [comment]
I think this is a non-issue since we are compiling our dependencies with `babel` and the compiled code requires the `@babel/runtime` package.

Example snippet from `@availity/api-core/lib/index.js` compiled code:

```js
"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

Object.defineProperty(exports, "__esModule", {
  value: true
});
Object.defineProperty(exports, "AvMicroservice", {
  enumerable: true,
  get: function get() {
    return _ms["default"];
  }
});
```

I believe the reason this was working before without the explicit dependency on `@babel/runtime` was because libraries like `reactstrap` also require `@babel/runtime` and so we just happened to have access to it inside of the node_modules folder.
