### ISSUE TITLE
Investigate navigator.sendBeacon() for analytics

### ISSUE THREAD

**Issue by robmcguinness** [Availity/sdk-js#60]
- https://www.smashingmagazine.com/2018/07/logging-activity-web-beacon-api
- IE 11 would be issue https://github.com/miguelmota/Navigator.sendBeacon

**Comment by robmcguinness** [comment]
Polyfill can work with IE11. All other browsers would be supported

**Comment by TheSharpieOne** [comment]
Not sure if this has changed, but security practices within the organization prevent sendBeacon from working. It's mostly due to sendBeacon being a POST where headers and such cannot be set and extra security checks and validations happen for POST within the middleware. You can probably get an exception for a specific analytics endpoint, but just something to keep in mind.

**Comment by robmcguinness** [comment]
good points. i was banking on being able to introspect post body for this particular route.
