### ISSUE TITLE
Error 'permissions.find is not a function'

### ISSUE THREAD

**Issue by jordan-a-young** [Availity/sdk-js#95]
When trying to run any function from AvAuthorizations, I am receiving the following error:

```
Uncaught (in promise) TypeError: permissions.find is not a function
    at index.js:114
    at Array.forEach (<anonymous>)
    at AvAuthorizationsReact.addPermissions (index.js:113)
    at index.js:85
```

Example usage:
```
async () => {
    const response = await AvAuthorizations.isAuthorized(permissionId, region);
}
```

**Comment by TheSharpieOne** [comment]
https://github.com/Availity/sdk-js/blob/842306824b2e7da0744ea10a906653ec3e815e90/packages/authorizations-core/src/index.js#L37

https://github.com/Availity/sdk-js/blob/842306824b2e7da0744ea10a906653ec3e815e90/packages/authorizations-core/src/index.js#L114

**Comment by nylon22** [comment]
Looks like `permissions` is not an array, which is causing error. Don't think we should be using `Array.prototype.find` anyways unless we include a polyfill with this package. IE11 doesn't support it: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

**Comment by GoPro16** [comment]
Yeah we want to stay away from pollyfills but you can either use the `filter` array method or include [lodash.find](https://bundlephobia.com/result?p=lodash.find@4.6.0)

**Comment by jordan-a-young** [comment]
I dug into the issue a little further. My assumption is the bug is stemming from the @availity/api-axios library being used.  When extending AvAuthorizations, from @availity/authorizations-core, if you pass in AvUserPermissionsApi rather than AvPermissionsApi, the issue is seemingly resolved. I believe this is because the responses differ for each api.

I agree lodash or another method that does not need to be polyfilled should ultimately be used.

**Comment by nylon22** [comment]
@jordan-a-young you're correct. `avPermissionsApi` returns the [raw response from axios/$http](https://github.com/Availity/sdk-js/blob/master/packages/api-core/src/resources/permissions.js). Notice, no `afterQuery`. `avUserPermissionsApi` returns [the permissions themselves](https://github.com/Availity/sdk-js/blob/master/packages/api-core/src/resources/userPermissions.js#L25). So, `authorizations-core` was trying to use `Array.prototype.find` on a structure like:
```json
{
    "data": {
        "permissions": [...]
    }
}
```

so, IMO - the change should:
- use `avUserPermissionsApi` instead of `avPermissionsApi`
- replace usage of `Array.prototype.find` with `Array.prototype.filter`
